name: Create an S3 Bucket

on:
  push:
    branches:
     - main
  workflow_dispatch:

permissions:
  id-token: write   # This is required for requesting the JWT
  #contents: read    # This is required for actions/checkout

jobs:
  creating_buckets:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6
      
      - name: Set up AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.IAM_ROLE }}
          aws-region: ${{ secrets.AWS_REGION }}
      
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v4

      - name: Initialize Terraform
        run:  terraform init
        working-directory: terraform

      - name: Terraform plan
        env: 
          BUCKET_NAME: ${{ secrets.BUCKET_NAME }}
        run: | 
          terraform plan \
            -var="bucket_name=$BUCKET_NAME"
        working-directory: terraform

      - name: Terraform apply
        env:
          TF_VAR_bucket_name: ${{ secrets.BUCKET_NAME }}
        run: terraform apply -auto-approve
        working-directory: terraform
  
  
  
  
  
  
  
        # listing_buckets:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Set up AWS Credentials
  #       uses: aws-actions/configure-aws-credentials@v4
  #       with:
  #         role-to-assume: ${{ secrets.IAM_ROLE }}
  #         aws-region: ${{ secrets.AWS_REGION }}      
      
  #     - name: List S3 Buckets
  #       env:
  #         AWS_REGION: ${{ secrets.AWS_REGION }}
  #       run: |
  #         echo "Listing S3 Buckets"
  #         aws s3 ls
        